# Generated by Django 5.1.2 on 2025-11-26 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('meet_you', models.JSONField(blank=True, default=dict)),
                ('course_idea', models.JSONField(blank=True, default=dict)),
                ('transformation_outcomes', models.JSONField(blank=True, default=dict)),
                ('existing_materials', models.JSONField(blank=True, default=dict)),
                ('brand_vibe', models.JSONField(blank=True, default=dict)),
                ('course_structure', models.JSONField(blank=True, default=dict)),
                ('media_content', models.JSONField(blank=True, default=dict)),
                ('legal_rights', models.JSONField(blank=True, default=dict)),
                ('platform_money', models.JSONField(blank=True, default=dict)),
                ('timelines_priorities', models.JSONField(blank=True, default=dict)),
                ('reviews_decision_makers', models.JSONField(blank=True, default=dict)),
                ('final_uploads', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='myApp_onboa_user_id_46ef9c_idx'), models.Index(fields=['session_id', 'status'], name='myApp_onboa_session_2e0539_idx')],
            },
        ),
    ]
