# Generated by Django 5.1.2 on 2025-11-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_client_tag_onboardingsession_access_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cloudinary_url', models.URLField(max_length=500)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255)),
                ('original_url', models.URLField(blank=True, max_length=500)),
                ('web_url', models.URLField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('folder', models.CharField(default='katek_ai/uploads', max_length=255)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='KaTek AI - All-in-One AI CRM & Growth Engine', max_length=200)),
                ('meta_description', models.TextField(default='Transform your business with KaTek AI - the complete CRM and growth platform.', max_length=500)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.TextField(blank=True, max_length=500)),
                ('og_image_url', models.URLField(blank=True, max_length=500)),
                ('twitter_card', models.CharField(blank=True, default='summary_large_image', max_length=50)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='WebsiteFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(default='© 2024 KaTek AI. All rights reserved.', max_length=500)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('footer_links', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='WebsiteHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_label', models.CharField(default='ALL-IN-ONE AI CRM', max_length=100)),
                ('main_headline', models.CharField(default='Stop juggling 17 tools. One system that connects everything.', max_length=500)),
                ('subheadline', models.TextField(blank=True)),
                ('primary_cta_text', models.CharField(default='Schedule Your Call', max_length=100)),
                ('primary_cta_link', models.URLField(blank=True, max_length=500)),
                ('secondary_cta_text', models.CharField(blank=True, max_length=100)),
                ('secondary_cta_link', models.URLField(blank=True, max_length=500)),
                ('background_image_url', models.URLField(blank=True, max_length=500)),
                ('dashboard_image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('story', 'Story Section'), ('platform', 'Platform Section'), ('outcomes', 'Outcomes Section'), ('ai_sales', 'AI Sales Section'), ('campaign_manager', 'Campaign Manager Section'), ('geo_distribution', 'GEO Distribution Section'), ('reputation', 'Reputation Section'), ('ai_websites', 'AI Websites Section'), ('personas', 'Personas Section'), ('testimonials', 'Testimonials Section'), ('final_cta', 'Final CTA Section')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('background_image_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Section',
                'verbose_name_plural': 'Website Sections',
                'ordering': ['sort_order', 'section_type'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=200)),
                ('author_title', models.CharField(blank=True, max_length=200)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
